require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'Guardfile'
    - 'tmp/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

# Disable for Rake tasks
Lint/HandleExceptions:
  Enabled: false

Style/Documentation:
  Enabled: false

# Prevent "Use nested module/class definitions instead of compact style."
Style/ClassAndModuleChildren:
  Enabled: false

#Metrics/AbcSize:
#  Max: 16
#
#Metrics/ClassLength:
#  Max: 175
#
#Metrics/MethodLength:
#  Max: 12

# Enabled disabled Cops
Style/CollectionMethods:
  Enabled: true

# Do not enforce Hash Style for now
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
